#!/usr/bin/env python3
"""Generate src/font_cp866.js from assets/cp866.f16.

The .F16 is a raw VGA 8x16 bitmap font: 256 glyphs, 16 bytes each (one byte
per scanline, MSB = leftmost pixel). assets/cp866.f16 is the FreeDOS CPIDOS
CP866 codepage font (glyphs indexed by CP866 byte value), so glyph N is the
character `bytes([N]).decode('cp866')`.

The emitted ES module carries:
  - GLYPHS_B64    : the 4096 font bytes, base64-encoded
  - CP866_BY_CHAR : { unicode-char -> byte } for every printable CP866 code
                    (0x20..0xFF, minus the 0x7F control), so the renderer can
                    map a JS string char back to its glyph index.

Run from repo root:  .venv/bin/python tools/make_font.py
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "assets", "cp866.f16")
OUT  = os.path.join(ROOT, "src", "font_cp866.js")

data = open(SRC, "rb").read()
assert len(data) == 4096, f"expected 4096 bytes, got {len(data)}"

b64 = base64.b64encode(data).decode("ascii")

# char -> byte map for printable codes. Skip C0/C1 control ranges and 0x7F;
# the renderer never needs control glyphs and space (0x20) is skipped anyway.
pairs = []
for byte in range(0x20, 0x100):
    if byte == 0x7F:
        continue
    ch = bytes([byte]).decode("cp866")
    # JSON-safe key: escape backslash and double-quote.
    key = ch.replace("\\", "\\\\").replace('"', '\\"')
    pairs.append(f'"{key}":{byte}')

map_body = ",".join(pairs)

js = f"""// AUTO-GENERATED by tools/make_font.py — do not edit by hand.
//
// Authentic FreeDOS CP866 8x16 VGA text-mode font (from
// viler-int10h/vga-text-mode-fonts, FONTS/SYSTEM/FREEDOS/CPIDOS30/CP866.F16),
// the codepage the original GOPNIK.EXE rendered under on a 2003 Russian-DOS PC.
//
// GLYPHS is 256 glyphs * 16 rows; row byte's bit 7 is the leftmost pixel.
// CP866_BY_CHAR maps a Unicode char to its glyph index (CP866 byte value).

export const FONT_W = 8;
export const FONT_H = 16;

const GLYPHS_B64 = "{b64}";

// Decode base64 -> Uint8Array(4096) once at module load.
export const GLYPHS = (() => {{
  const bin = atob(GLYPHS_B64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}})();

export const CP866_BY_CHAR = {{{map_body}}};
"""

open(OUT, "w", encoding="utf-8").write(js)
print(f"wrote {OUT} ({len(js)} bytes, {len(pairs)} char->byte entries)")
